### ISSUE TITLE
Too few ports

### ISSUE THREAD

**Issue by SymmetricColors** [anujkaliaiitd/dpdk_cpp#1]
when i try to run the code i get "Too few ports".
i have two vfio port and two igb uio
can you please help me to run the code?
and one more question:
can you explain for me why this code uses vfio instead of igb uio?

**Comment by anujkaliaiitd** [comment]
It uses the first port available to DPDK (see `kAppPortId`), which in your case is probably vfio. This constant can be changed to any port.

I've currently not tested the code with vfio, and a vfio PMD is not currently linked in (see `rte_pmd_ixgbe` and friends in CMakeLists.txt). The missing PMD could be why this application fails to detect a port. I would recommend disabling all vfio ports if possible.
